# Generated by Django 3.0.8 on 2020-08-12 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to=settings.AUTH_USER_MODEL)),
                ('watch_list', models.ManyToManyField(blank=True, related_name='user_watchlist', to='auctions.Auction_Listing')),
            ],
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
