# Generated by Django 3.0.8 on 2020-08-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200812_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watch_list',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watch_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to='auctions.Auction_Listing'),
            preserve_default=False,
        ),
    ]
