# Generated by Django 3.0.8 on 2020-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200813_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='user',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
