# Generated by Django 3.0.8 on 2020-08-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200814_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auction_Listing_set', to='auctions.Auction_Listing'),
        ),
    ]
