# Generated by Django 3.0.8 on 2020-08-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200814_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch_list',
            field=models.CharField(max_length=64),
        ),
    ]
