# Generated by Django 3.0.8 on 2020-08-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200815_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='Auction_user',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='auction_winner',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
