# Generated by Django 3.0.8 on 2020-09-20 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200910_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='no_of_likes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
