# Generated by Django 3.0.8 on 2020-09-21 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200921_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='no_of_likes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_likes', models.IntegerField()),
                ('likes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='network.Posts')),
            ],
        ),
    ]
