# Generated by Django 3.0.8 on 2020-09-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200921_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followers_num',
            new_name='followings',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following_num',
            new_name='no_of_followers',
        ),
    ]
