# Generated by Django 3.0.8 on 2020-09-22 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200921_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='no_of_followings',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='followers',
            field=models.ManyToManyField(related_name='followers_of_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followings',
        ),
        migrations.AddField(
            model_name='follow',
            name='followings',
            field=models.ManyToManyField(related_name='followings_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
